version: '3.8'
services:
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1337:1337"
    command: yarn start
    environment:
      REDIS_PORT: 6379
    volumes:
      - ./public:/usr/backend/public
    restart: always
    links:
      - cache
      - db
