version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=147258
      - POSTGRES_DB=backendmanganext
    container_name: postgres_mangas

    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5433:5432
  cache:
    container_name: redis
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/redis/cache
volumes:
  cache:
    driver: local
  db:
    driver: local
