version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=147258
      - POSTGRES_DB=backendmanganext
    container_name: postgres_mangas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data


  cache:
    container_name: redis
    image: redis:7.0.4-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - cache:/redis/cache


volumes:
  cache:
    driver: local
  db:
    driver: local

