version: '3.8'
services:
  downloader:
    build: .
    volumes:
      - ./downloads.json:/downloader/downloads.json
      - ./settings.json:/downloader/settings.json
    command: python main.py
    restart: always
